apiVersion: v1
kind: Service
metadata:
  name: postgre-master
  labels:
    app: postgre
    role: master
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgre
    role: master
    tier: backend