apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      app: vote      
  replicas: 3
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: pragra/vote
        imagePullPolicy: Always
        ports:
        - containerPort: 5000