apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: pragra/vote:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000